### ISSUE TITLE
support for tables

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio2grafana#10]
Would be great if this would allow users to output data in tables as well

**Comment by kaspernissen** [comment]
Do you plan on supporting this anytime soon? 

I'm trying to display a query like this in a grafana table:
```
res.statusCode >=200 | groupby(field=k8s.labels.app, function=percentile(responseTime,percentiles=[95,99])) | sort(_95)
```

But, it don't seem to be possible with the current implementation

**Comment by Crevil** [comment]
Any work being done regarding this?

**Comment by jgn-epp** [comment]
I have done some work on this, will do a pull request tonight. Hopefully it will be merged 🙏

**Comment by Crevil** [comment]
Nice. 🙏

**Comment by AlexanderBrandborg** [comment]
This has been added in https://github.com/humio/humio2grafana/pull/34. Thanks @jgn-epp!
