### ISSUE TITLE
plugin not working anymore on cloud grafana

### ISSUE THREAD

**Issue by k-dannemand** [humio/humio2grafana#107]
Hey, we use your plugin for grafana.
https://urldefense.proofpoint.com/v2/url?u=https-3A__grafana.com_grafana_plugins_humio-2Ddatasource_-3Ftab-3Dinstallation&d=DwIBaQ&c=08AGY6txKsvMOP6lYkHQpPMRA1U6kqhAwGa8-0QCg3M&r=xAbLeWeXnoPP4pWLswhdlBsRAW72Q7tPmgTIpUz1HUQ&m=13eBiY7tLALIoKK9uBTgZWLQF1vi6OYrjs7atOBTC6QyC8SfvDX2JhNwrPlfftr3&s=-bMnweEHItcHw1UXRQry7iey6OaImBvUq_st7ebmm6U&e=
And it seems it has stopped working since they rolled grafana cloud up to
version 9.x.x
I can install it just fine.
but it never comes in as a data source in grafana. we use it for quite a
few alarms so it's a big problem for us :(
![graf](https://user-images.githubusercontent.com/19834594/185922913-988b0d66-7ba8-49f4-8ebb-7212a46e937b.png)

**Comment by AlexanderBrandborg** [comment]
Hej @k-dannemand , thanks for reporting this.
We'll look into it.

**Comment by AlexanderBrandborg** [comment]
@k-dannemand ,
I've had a look. Tried upgrading my local version of Grafana from 8.2 to 9.1.
Running locally with my development version of the plugin, there doesn't seem to be an issue.

So I think I might need a bit more info on where things are going wrong :) 

As I understand it, you are installing the plugin via:
https://grafana.com/grafana/plugins/humio-datasource/?tab=installation

And then in the Grafana UI, you are not able to create a Humio data source under:
`Configuration -> Data Sources` -> `Add New Datasource`

Does this mean that Humio doesn't show up on this list?
![image](https://user-images.githubusercontent.com/14312681/186640859-e46cfb0c-89e5-436e-a2d3-bc98259b6071.png)

**Comment by k-dannemand** [comment]
@AlexanderBrandborg Correct! 
![gra](https://user-images.githubusercontent.com/19834594/186669849-03bc9ad0-da09-4df0-92c8-1f0b346c5301.png)

**Comment by AlexanderBrandborg** [comment]
That's strange, something to do with how we're showing up in the marketplace. Will figure this out :)

**Comment by tolzhabayev** [comment]
Hey there,

please change the https://github.com/humio/humio2grafana/blob/master/src/plugin.json#L33 to 

`"grafanaDependency": ">=8.0.0",`

and submit a plugin update @AlexanderBrandborg that will make it show up properly again. 

docs: https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#properties-1

**Comment by AlexanderBrandborg** [comment]
Thank you @tolzhabayev :) 
Had a feeling it was something like that. I've submitted an updated version of the plugin for review by Grafana.
Will keep you updated.

**Comment by AlexanderBrandborg** [comment]
@k-dannemand, the update should have been published as version 3.3.1.
Can you test whether it works now?

**Comment by k-dannemand** [comment]
@AlexanderBrandborg Yes i can see i now. I tried just to upgrade the plugin but that did not work. i had to remove it and install it again, but yes now i see it, thanks alot :)

**Comment by AlexanderBrandborg** [comment]
Alright, glad it worked out.
Closing this issue for now :)

**Comment by k-dannemand** [comment]
@AlexanderBrandborg i dont know if this is related but when i try to auth with my token i just get "bad gateway"
but it fills out the url from the token, so it should be right, right ?
![bad](https://user-images.githubusercontent.com/19834594/186899365-15d54cd5-b177-407c-a102-1d9f2597541d.png)

**Comment by AlexanderBrandborg** [comment]
I can contact the cloud fine.
You shouldn't need to input more than `https://cloud.humio.com` for the url, and then use your personal access token, not ingest token, for auth.
![image](https://user-images.githubusercontent.com/14312681/186900737-e6b6d387-2426-457e-b32c-e8e27bcde2d3.png)
