### ISSUE TITLE
Submit plugin to Grafana.com

### ISSUE THREAD

**Issue by mwl** [humio/humio2grafana#12]
See https://github.com/grafana/grafana-plugin-repository

**Comment by mwl** [comment]
Just curious, why was the PR closed again grafana/grafana-plugin-repository#225?

**Comment by mwl** [comment]
see grafana/grafana-plugin-repository#227

**Comment by mwl** [comment]
I think we should rename the plugin to just "Humio"
![skaermbillede 2018-02-07 kl 10 50 51](https://user-images.githubusercontent.com/81906/35909802-eb0421a0-0bf4-11e8-9ffd-20720f4caeca.png)

**Comment by AlexanderBrandborg** [comment]
Closing as we've decided internally not to move ahead with this right now.
