### ISSUE TITLE
Rename name of plugin in Datasource list

### ISSUE THREAD

**Issue by mwl** [humio/humio2grafana#14]
I think we should rename the plugin to just say "Humio"
![skaermbillede 2018-02-07 kl 10 50 51](https://user-images.githubusercontent.com/81906/35909910-37fa595c-0bf5-11e8-8317-0fd8955bb23c.png)

**Comment by xorsnn** [comment]
@mwl it doesn't make sense: in grafana plugin named "Grafana"

**Comment by xorsnn** [comment]
@mwl maybe name it "Humio"

**Comment by mwl** [comment]
Confirmed
