### ISSUE TITLE
Improve defaults for Humio Datasource

### ISSUE THREAD

**Issue by mwl** [humio/humio2grafana#15]
Not sure why "proxy" is default for access.

Can't we put our access token into the auth section?

![skaermbillede 2018-02-07 kl 10 52 50](https://user-images.githubusercontent.com/81906/35909978-6acfa0f8-0bf5-11e8-85a7-8bc6b05da16d.png)

**Comment by xorsnn** [comment]
@mwl 
grafana proxy means that requests to the datasource are made by grafana backend, otherwise they will be made directly from brouser, from my point of view it makes sense to leave proxy as a default way of communication

**Comment by mwl** [comment]
Ah! Okay. I thought it was HTTP Proxy.
