### ISSUE TITLE
Grafana feedback

### ISSUE THREAD

**Issue by mwl** [humio/humio2grafana#17]
Some feedback from the Grafana grafana/grafana-plugin-repository#227 guys
- [x] Is the access key supposed to be secret? If so, you should use secureJsonData (instead of jsonData) on the config page to save it so that it will be encrypted.
- [x] It is not possible to delete a query in the query editor after adding it.
- [x] The "Open query in Humio" link does not work for me.

I believe I had confirmed the remove query issue. He's right about the first one. It _is_ a secret and should be hidden.

**Comment by xorsnn** [comment]
only documentation that I found https://community.grafana.com/t/adal-within-a-datasource-plugin/3435/12

**Comment by AlexanderBrandborg** [comment]
Closing as all feedback has been considered and implemented
