### ISSUE TITLE
Changing time ranges don't seem to refetch data

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio2grafana#2]
Grafana version: 4.6.2

Humio query in graph: 
```
k8s.labels.app=authentication grpc.service=authentication.Authentication | timechart(buckets=1000,function=count(), series=grpc.method, unit=/s)
```

Default time ranges for dashboard: Last 3 hours

**Grafana**
![screen shot 2018-01-10 at 12 52 53](https://user-images.githubusercontent.com/4429108/34771558-3a5f2034-f605-11e7-97dd-113264a50bb9.png)

**Humio**
![screen shot 2018-01-10 at 12 54 04](https://user-images.githubusercontent.com/4429108/34771611-69b32a74-f605-11e7-982d-d4b1808497a0.png)

When opening the dashboards, everything seems fine. However, if changing the time ranges using the Quick Ranges, the data is not populated. 

**Example of switching to Last 24 hours:**
![screen shot 2018-01-10 at 12 55 03](https://user-images.githubusercontent.com/4429108/34771638-8ce71b7c-f605-11e7-91a9-5e710f71e21a.png)

**Comment by kaspernissen** [comment]
Same problem for Panel: *Singlestat*

**Comment by xorsnn** [comment]
@kaspernissen do you have data for 24 hours in humio? How does humio chart for the last 24 hours look like?

**Comment by kaspernissen** [comment]
@xorsnn yes we do have data for 24 hours in Humio. 

Humio:
3 hour
![humio3h](https://user-images.githubusercontent.com/4429108/34823507-e8ae8088-f6ca-11e7-953c-e9211ca58935.png)
24 hour
![humio24h](https://user-images.githubusercontent.com/4429108/34823509-ea7973c8-f6ca-11e7-833d-83be8cbf09f0.png)

Grafana:
3 hour
![grafana3h](https://user-images.githubusercontent.com/4429108/34823525-fb6ef96e-f6ca-11e7-995e-feda8b96decb.png)
24 hour
![grafana24h](https://user-images.githubusercontent.com/4429108/34823526-fd140b7e-f6ca-11e7-8c5f-5fa9d8ebf3a1.png)

**Comment by kaspernissen** [comment]
With the latest commit, this is now working! Thanks.
