### ISSUE TITLE
Queries from Grafana doesn't yield same result as in Humio

### ISSUE THREAD

**Issue by lieberkind** [humio/humio2grafana#23]
The query `loglevel=* | groupBy(loglevel)` yields different results in Grafana and Humio.

**Comment by AlexanderBrandborg** [comment]
Hey @lieberkind, is this still an issue with the current version of the master branch? I have not been able to replicate the issue.

**Comment by AlexanderBrandborg** [comment]
Closing this issue, feel free to reopen if necessary.
