### ISSUE TITLE
Migrate to use the graphql api instead of the "rest" style api on Humio.

### ISSUE THREAD

**Issue by mortengrouleff** [humio/humio2grafana#30]
Graphql is the recommended API on Humio these days. Update the plugin to no longer make use of the old api.

**Comment by jgn-epp** [comment]
I wouldn't mind helping out with this, but I'm unsure if the maintainer(s) of this plugin are still active, so would be nice to have that confirmed before I start.

**Comment by mortengrouleff** [comment]
We're around. I'll see if someone volunteers to take a look at your PRs.

**Comment by jgn-epp** [comment]
Alright, thanks 🙂

**Comment by AlexanderBrandborg** [comment]
https://github.com/humio/humio2grafana/pull/38 has been successfully merged, so closing this issue. Thanks @domdomegg .
