### ISSUE TITLE
Humio Datasource crashes on grafana 6.7.2

### ISSUE THREAD

**Issue by nikobearrr** [humio/humio2grafana#45]
**Describe the bug**
When creating a new datasource in grafana and select "Humio" the website crashes with an error

**To Reproduce**
1. Open Grafana
2. Go to Datasources
3. Click on "Add data source"
4. Select "Humio"
5. Observe bug

**Expected behavior**
I can put my Humio cluster information and save datasource

**Screenshots**

```
Unexpected token '<' Evaluating http://localhost:3000/public/plugins/humio-humio2grafana-datasource/module.js Loading plugins/humio-humio2grafana-datasource/module
Data Source Error
```

![image](https://user-images.githubusercontent.com/8693064/78260306-de6e8b80-750e-11ea-8f79-3f3796423033.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4 (19E266)
 - Browser: Chrome Version 80.0.3987.149 (Official Build) (64-bit)
 - Version: Latest humio2grafana, Grafana 6.7.2

**Aditional information**

When I try to delete the datasource I get a popup saying `Missing valid datasource id`

![image](https://user-images.githubusercontent.com/8693064/78260411-fd6d1d80-750e-11ea-90f1-786fc0431d44.png)

**Comment by AlexanderBrandborg** [comment]
Hi, thank you for reaching out to us about this issue :)  We've not been able to replicate this it while working on Windows with Grafana 6.7.2. Have you attempted to build the plugin from the master branch yourself? It occurs to me that since the released plugin was build on Windows, it might not work on Mac/Linux.

**Comment by nikobearrr** [comment]
Hello @AlexanderBrandborg. I haven't build the plugin itself, I have installed it like I did before - I copy the src into my grafana. Perhaps that's what I am missing. But I didnt' do it before - I just copied the dest folder.

In my original ticket perhaps I didn't give the full information. I am running grafana 6.7.2 in docker

**Comment by nikobearrr** [comment]
Hello, that seems to have worked. I built it first and copied to grafana. I didn't see the installation procedure has changed. Thank you
