### ISSUE TITLE
How to configure Grafana to have Humio datasource

### ISSUE THREAD

**Issue by nikobearrr** [humio/humio2grafana#46]
After I have figured out in https://github.com/humio/humio2grafana/issues/45 I didn't follow the correct steps for the installation, now I am facing another issue - I cannot add my humio cluster as datasource

I am running:
- Grafana 6.7.2 in docker
- Humio Version: 1.8.9--build-12366--sha-b1c1acc607 (on-premise)

Based on the instructions here: https://docs.humio.com/integrations/other/grafana/ (I think the formatting is a bit off)
Point 3) on how to configure a datasource says: "Set Humio access token. Please make sure not to use an ingest token, as it cannot be used to query data from your Humio instance.". But where do I get this Humio access token from? 

I googled "Humio access token" and I got this page: https://docs.humio.com/cluster-management/security/root-access/ But this says "The token is re-created every time the server starts". I also tried that specific token, but it couldn't connect. I don't remember having to put a Humio access token in the previous version of humio2grafana, but perhaps I am missing something again?

Any help would be appreciated

**Comment by SaaldjorMike** [comment]
Hi @nikobearrr 

You should be able to visit `$YOUR_HUMIO_URL/settings` and grab an API token for your account, then use that as the access token. 

You definitely don't want to use any type of token with delete/root privileges as the access token for the Grafana plugin. The local-admin-token is generated every time Humio restarts, and is a root token so I'd strongly suggest not using it for this.

Ideally you'd be able to use a read-only token specifically for this purpose.

A potential workaround to get credentials that are not tied to your main user (if that has delete/root privileges):
- Sign up with an additional user
- Assign read-only access to that user
- Login to the new user and visit `$YOUR_HUMIO_URL/settings`, grab the API token

If you're hosting your own Humio installation and you're in a situation where you have to ensure no-one can log in to the user being used for the Grafana plugin:
- Add a dummy user to your system
- SSH into the machine running Humio
- Find the API token for the dummy user in the file: `$DATA_DIR/humio-data/global-data-snapshot.json` (do not edit the file!)

Perhaps this should be more clear @AlexanderBrandborg ?

Hopefully this helps a bit to get you a little further.

**Comment by nikobearrr** [comment]
Hello @SaaldjorMike,
Thank you for your thorough answer.

We are running humio without authentication so when I go to myurl.com/settings I see this:

![image](https://user-images.githubusercontent.com/8693064/78777554-ced9c180-79aa-11ea-90ed-e590f97773d7.png)

**Comment by AlexanderBrandborg** [comment]
@nikobearrr I honestly haven't seen this setup before, but it seems Grafana worked for you on the old version of the plugin? There's always been a field to add an API token though.

If it worked before try this:
- Create an entirely new data source in Grafana
- Enter only your URL
- Press save & test
- Try to use use the new datasource in one of your panels.

How does that work out?

**Comment by nikobearrr** [comment]
Hello,

I provision my Humio datasource like this in Grafana:

```
 - name: Humio
   type: humio-humio2grafana-datasource
   access: proxy
   orgId: 1
   url: http://humio:8080
   isDefault: false
   editable: false
   version: 2
   jsonData:
     humioToken: ""
     keepCookies: []
```

When I run grafana I can see the Humio datasource correctly conigured.
If I press "Test" I get "HTTP Error Bad Request" under the Humio access token.
However, I am able to query the humio cluster with queries.

That is using grafana 6.7.2 and latest humio2grafana (I am not sure which version is atm) as of time of writing.

Thank you for your help.
