### ISSUE TITLE
Annotation Queries

### ISSUE THREAD

**Issue by AlexanderBrandborg** [humio/humio2grafana#49]
**Is your feature request related to a problem? Please describe.**
The Plugin feature currently does not support annotation queries. This should be used to query events from Humio, which can be used to annotate interesting points in time on timechart widgets.

**Describe the solution you'd like**
Implement the AnnotationsQueryCtrl class and associated frontend template to support the feature. An annotation query should just be a regular Humio filter query, and each event returned is turned into an annotation. The tags on the annotation are defined by the Grafana user, but the text of an annotation should be extracted from a user-defined field or substring for each event. 

**Describe alternatives you've considered**
This will only allow for annotations for specific timestamps, not regions of time that can be annotated. However this doesn't seem to fit well with the data that can be returned from Humio so it doesn't seem relevant as of yet.

**Additional context**
Annotations in Grafana:
https://grafana.com/docs/grafana/latest/reference/annotations/

A bit about implementing them in a plugin:
https://grafana.com/docs/grafana/latest/developers/plugins/legacy/data-sources/

**Comment by Suzanna-Volkov** [comment]
This issue should be fixed with the new release v.3.0.0.
