### ISSUE TITLE
Support for Grafana variables

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio2grafana#51]
**Is your feature request related to a problem? Please describe.**
It's not directly a problem, however, it's a bit frustrating, that it's not possible to use variables with this data source yet. We use Grafana to visualize most of our stuff, and it would be nice to have this functionality added as well so that our developers can focus on grafana, rather than using different dashboard solutions. 

**Describe the solution you'd like**
Grafana has support for variables. I would like humio to support similar functionality to what is possible with the Prometheus data source.

When adding a variable, e.g. I want to provide a query that will fetch data from humio. An example could be the list of teams ingesting logs. This list along with an all option should then be presented on the dashboard as a dropdown, to either select one, many, or all. Depending on the selection each query performed in the dashboard would change accordingly. 

Let's say i have a chart displaying  level=error. I want the query to be something like: `level=error k8s.labels.squad=$squad | timechart()`. If all is selected, `*` should be used instead.

**Describe alternatives you've considered**
None.

**Additional context**
The Prometheus data source for grafana does this pretty well, I would love to see a similar experience with this integration as well.

**Comment by AlexanderBrandborg** [comment]
@kaspernissen we have been working on a beta of this feature in https://github.com/humio/humio2grafana/tree/issue/53/upgrade-to-react. If you want, you can try it out and see if it works out for you. Installation guide resides in the README.

**Comment by Suzanna-Volkov** [comment]
This issue should have been resolved with the release v.3.0.0. If a problem persists, please create a new issue. :)
