### ISSUE TITLE
Upgrade plugin to React

### ISSUE THREAD

**Issue by AlexanderBrandborg** [humio/humio2grafana#53]
**Is your feature request related to a problem? Please describe.**
Some features cannot be implemented right now, because the plugin uses AngularJS, where Grafana is moving towards React.

**Describe the solution you'd like**
Build the project anew, but with React

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Suzanna-Volkov** [comment]
This issue should be fixed with the release v3.0.0.
