### ISSUE TITLE
"Open query in Humio" does not work with grafana 7.0.4

### ISSUE THREAD

**Issue by nikobearrr** [humio/humio2grafana#57]
**Describe the bug**
We are running grafana 7.0.4 with humio2grafan v2.0.1
When I click on "Open query in Humio" I get grafana's 404 page

**To Reproduce**
1. Create new dashboard in grafana with Humio data source
2. Leave default query, select a repository
3. Click on "Open query in Humio"

**Expected behavior**
I expect to open my humio with the repository I am querying.
Instead, it opens `http://localhost:3000/undefined/myhumiorepo/search?query=timechart().......`
However, it should have opened `http://localhost:5000/myhumiorepo/search?query=timechart().......` since humio is running `localhost:5000`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, latest
 - Version: ?

**Comment by Suzanna-Volkov** [comment]
@nikobearrr I have managed to reproduce your issue, and I will see what I can do to fix it. :)

**Comment by Suzanna-Volkov** [comment]
Hi @nikobearrr, I have created a branch, issue/57/open-query-in-humio, with a potential fix. Can you possibly check it out and see whether it works for you?

**Comment by Suzanna-Volkov** [comment]
This issue should be fixed with the new release. If there still is a problem, please create a new issue. :)

**Comment by nikobearrr** [comment]
Hi @Suzanna-Volkov thank you for working on the issue. I didn't get to test the branch, but I will test the v3.0.0 at some time in the near future. I will let you know if there are any issues related to this.
