### ISSUE TITLE
BUG: Same query for different repositories will only run for 1 repository

### ISSUE THREAD

**Issue by nikobearrr** [humio/humio2grafana#68]
**Describe the bug**
Running the same query for different repositories will mix-up the graphs

We have 2 repositories on which we can run the same queries. When we create the 2 graphs in the dashboard they look exactly the same, although we are sure (when looking at the same queries in Humio) that data is not the same. 

It seems that the query is globally (dashboard context) tied/linked to a repository and since we add the same query to another panel with different repository it uses some cache/lookup and uses only the first repository.

**To Reproduce**
1. Create a new dashboard
2. Add new panel
3. Add Humio query
4. Write a humio query 
5. Select repository "repo1"
6. Add new panel
7. Add the same Humio query as per step #3
8. Select repository "repo2"
9. Observe data looks correct when in edit mode
10. Go to the dashboard (where you can see the 2 graphs)
11. Both panels, even though they are wired to different repositories, show the same data

**Expected behavior**
I would expect we can run the same query for multiple repositories and the queries are run per repository and not on the first one only.

**Screenshots**
If cannot be reproduced by the steps I gave I will try to gather some screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v3.0.4

**Comment by nikobearrr** [comment]
Actually I just found out this happens only prior to saving. Perhaps that can be some guidance.

**Comment by AlexanderBrandborg** [comment]
@nikobearrr thanks, we will look into this.

**Comment by AlexanderBrandborg** [comment]
Hey so I just tried replicating this on current master of this plugin and with Grafana 7.2.1, but I've not been able to replicate given the steps above. I have attached a few screenshots, for clarity's sake.  Maybe you could screenshot me your case? Only difference I can tell here is that I'm running on Linux, though I'm not sure what effect that'll have, and I'm not sure of your Grafana version.

![Screenshot from 2020-10-12 09-06-17](https://user-images.githubusercontent.com/14312681/95715627-78578380-0c6a-11eb-97a0-2963217c870d.png)
![Screenshot from 2020-10-12 09-06-48](https://user-images.githubusercontent.com/14312681/95715630-78f01a00-0c6a-11eb-800c-72c2f89c5da6.png)
![Screenshot from 2020-10-12 09-07-02](https://user-images.githubusercontent.com/14312681/95715631-7988b080-0c6a-11eb-8000-ad2711735117.png)

**Comment by AlexanderBrandborg** [comment]
Hi @nikobearrr, 
I have released some new versions of the plugin since our last convo. 
Is this still an issue for you?

**Comment by nikobearrr** [comment]
Hi @AlexanderBrandborg sorry for the late reply.
I haven't had the opportunity to neither test it or reproduce it. I'd suggest to close it. In case I come across it again I will create an issue.
