### ISSUE TITLE
Wrong queryStart time sent to Humio when non-predefined interval chosen in Grafana

### ISSUE THREAD

**Issue by fyang13** [humio/humio2grafana#72]
**Describe the bug**
While using Humio Grafana plugin used as annotation source, the "queryStart" time passed to Humio query is always 24hrs if non-predefined interval was chosen.

**To Reproduce**
1. Go to time picker in Grafana, instead of using predefined interval, specify custom time range like:
    From: now-3d
    To : now
2. Click on 'Apply time range'
3. Inspect from Chrome developer console, the query job actually has "queryStart" set to 24hrs ago, select something like now-4d, now-1M etc. all lead to "queryStart" set to 24hrs ago. But if specify exact time range, the "queryStart" time was passed correct.

**Expected behavior**
Correct starting time passed to Humio query when "-Xd" or "-XM" is used for started time in Grafana time picker.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: chrome v86.0.4240.198
 - Grafana: 7.2.0
 - Humio plugin: 3.0.5

**Comment by AlexanderBrandborg** [comment]
Hey @fyang13, thanks for reporting this. 
I've been able to reproduce the error and will try to fix it.

**Comment by AlexanderBrandborg** [comment]
Hi @fyang13, the fix is now on master.
Note that for time ranges not supported for live queries in Humio, static query jobs will be used.
