### ISSUE TITLE
handling of no data in graphs

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio2grafana#8]
it looks like handling of no data is resulting in an error in the console, and infinite spinner.. when expanding the timespan to include time where the query will return data there's no issues.

![screen shot 2018-01-18 at 08 11 40](https://user-images.githubusercontent.com/4429108/35085222-f44e5898-fc27-11e7-929d-4188d7198dbc.png)

**Comment by xorsnn** [comment]
@kaspernissen commit f40d010f91faa68d7dbf11bc7f72b3c1f9afa34d should fix the issue

**Comment by kaspernissen** [comment]
Verified and working.
