### ISSUE TITLE
Humio query does not show on grafana

### ISSUE THREAD

**Issue by nikobearrr** [humio/humio2grafana#80]
**Describe the bug**

I am trying to use the Humio "Ingest" query into grafana, but no data shows

**To Reproduce**

1. go to humio repo in humio
2*. copy the code for Ingest Per Repo (bytes per day)
3. paste in grafana

* this is the query as shown in my humio query 
```
#type=humio #kind=metrics name=/^ingest-bytes(\/[^\/]+)?\/(?<repo>.*)$/
| timechart(repo,
       function={ groupby(#vhost, function=avg(m5)) | sum(_avg)},
       limit=30, unit="bytes/sec to bytes/day")
```

**Expected behavior**
I can see the same graph as I see on Humio. Currently all the repositories show, but no graphical data

**Desktop (please complete the following information):**
 - Humio 1.20.4
 - Grafana 7.4.3
 - humio2grafana 3.2.3
 
**Additional context**
I am not sure if it should "just work". But I'd expect that I can copy-paste any query that I can see in Humio and show it in grafana.

**Comment by AlexanderBrandborg** [comment]
Hi @nikobearrr,
Thanks for bringing up this bug. 

I have been able to reproduce it and it seems there's something wrong with how we convert the time-series data after receiving it from Humio. I'll have a look at this soon and will note you when I find a solution. :- )

**Comment by AlexanderBrandborg** [comment]
I've just released v3.2.4 of the plugin, which contains a fix for this.
You can currently download that version from this repo, or wait a few days and it should be available signed through Grafana itself.
Thanks for bringing this to our attention @nikobearrr  :- )

**Comment by nikobearrr** [comment]
Thank you for the fix @AlexanderBrandborg. I will give it a go soon

**Comment by nikobearrr** [comment]
Hi @AlexanderBrandborg
I have just tested 3.2.4 and I get the same result when trying the same query.

**Comment by AlexanderBrandborg** [comment]
Hi @nikobearrr,
You mean you get the same result in Grafana as in Humio?

**Comment by nikobearrr** [comment]
Sorry I was not clear enough.

What I meant to say is that nothing has changed. But I just tested again and it seems to work. I am a bit confused. But I can confirm I can paste the Humio query into grafana and it works as expected.

**Comment by AlexanderBrandborg** [comment]
No problem, thanks for clearing it up.

I think what you're experiencing is that the new plugin version wasn't loaded before? It usually takes a restart of Grafana and some browser refreshing before you're sure a plugin update is loaded.

Glad to hear that it's working now though! Feel free to reach out if you run into more issues :- )
