### ISSUE TITLE
Allow for non-admins to use "Open Query in Humio" link

### ISSUE THREAD

**Issue by jpdstan** [humio/humio2grafana#90]
**Describe the bug**
This link works only for Admin users on grafana. Why? Because this [queries the datasource api](https://github.com/humio/humio2grafana/blob/572ee154605df6ab94516308fa4b1a141eb1620b/src/HumioQueryEditor.tsx#L51) to grab the host URL, which seems to be locked down to only Admins. Judging from the [Datasource Permissions API](https://grafana.com/docs/grafana/latest/http_api/datasource_permissions/), it looks like it only affords non-admins to query it, but not read it (strangely enough). 

**Expected behavior**
Clicking the link should take me to our humio install. Currently the link does not work as the host in the URL is not populated

**Screenshots**

![image](https://user-images.githubusercontent.com/5893781/122310107-76625600-cec4-11eb-8d57-57494b5cd629.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS catalina
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 7.3.x

**Comment by jpdstan** [comment]
This might also be interpreted as a feature request for Grafana to allow for more granular access controls in their datasource permissions api https://grafana.com/docs/grafana/latest/http_api/datasource_permissions/

![image](https://user-images.githubusercontent.com/5893781/122310908-ddccd580-cec5-11eb-91e6-a231d7d8f9fe.png)

**Comment by AlexanderBrandborg** [comment]
Hi @jpdstan, thanks for bringing this to our attention.
It's correct that we query the datasource endpoint to get the URL, so I think you're right in your assesment that the problem stems from there. I'll see I can work around this somehow for the next release of the plug in :- )
Thanks.

**Comment by jpdstan** [comment]
Thanks so much @AlexanderBrandborg !

**Comment by AlexanderBrandborg** [comment]
@jpdstan Hey.
I have created a fix for this. It's in v3.3, which should go out in a few weeks depending on the plugin review process :- )
