### ISSUE TITLE
Support region annotation

### ISSUE THREAD

**Issue by fyang13** [humio/humio2grafana#92]
Can support be added for region annotation? 

It seems additional "timeEnd" field need to be populated for region annotation:
https://grafana.com/docs/grafana/latest/http_api/annotations/

**Comment by AlexanderBrandborg** [comment]
Hi @fyang13 , I'll look into supporting this.
How would you expect the `timeEnd` value to be defined? 
Right now the `time` of an annotation is just the timestamp of the corresponding event. Would the `timeEnd` be a user-defined field on the same event in your eyes? :)

**Comment by fyang13** [comment]
I think it can be just a field return from the query? This way, user has flexibility to extract it from multiple events or single event. So maybe a place in UI allowing user to specify which {{field}} will be assigned as "timeEnd"?

**Comment by AlexanderBrandborg** [comment]
@fyang13 Hey.
I have added a field in v3.3 of the plugin as discussed above :)
